[project]
name = "intertia-django-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "django>=5.2.5",
    "django-vite>=3.1.0",
    "honcho>=2.0.0",
    "inertia-django>=1.2.0",
]
